# Generated by Django 4.2.5 on 2023-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
